config/routes.rb
Rails.application.routes.draw do

  resources :stocks
  
  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  devise_scope :admin do
    authenticated :admin do
      namespace :admins do
        get 'dashboard/index', as: :authenticated_root
        patch 'dashboard/:id/update',to:'dashboard#update' , as: :approved
      end
    end
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    authenticated :user do
      namespace :users do
        get 'dashboard/amzn', as: :authenticated_root
        get 'dashboard/fb'
        get 'dashboard/twtr'
        get 'dashboard/nflx'
        post 'dashboard/amzn',to:'dashboard#buy_amzn', as: :buy
        post 'dashboard/fb',to:'dashboard#buy_fb', as: :buyfb
        post 'dashboard/twtr',to:'dashboard#buy_twtr', as: :buytwtr
        post 'dashboard/nflx',to:'dashboard#buy_nflx', as: :buynflx
      end
    end
  end
  
  devise_scope :broker do
    authenticated :broker do
      namespace :brokers do
        get 'dashboard/amzn', as: :authenticated_root
        get 'dashboard/fb'
        get 'dashboard/twtr'
        get 'dashboard/nflx'
        post 'dashboard/amzn',to:'dashboard#buy_amzn', as: :buy           #this should be sell
        post 'dashboard/fb',to:'dashboard#buy_fb', as: :buyfb             #this should be sell
        post 'dashboard/twtr',to:'dashboard#buy_twtr', as: :buytwtr       #this should be sell
        post 'dashboard/nflx',to:'dashboard#buy_nflx', as: :buynflx       #this should be sell
      end
    end
  end

  devise_for :brokers, path: 'broker', controllers: {
    sessions: 'brokers/sessions',
    registrations: 'brokers/registrations'
  }

  root to: "home#index"
end

app/controllers/admins/dashboard_controller.rb
class Admins::DashboardController < ApplicationController
  def index
    @users = User.all
    @brokers = Broker.all.order(approved: :desc)    #sort by status
  end

  def update
    @broker = Broker.find(params[:id])
    @broker.update(:approved=>true)

    redirect_to admins_authenticated_root_path, notice: "user was successfully approved."
  end
  
  private
  # Only allow a list of trusted parameters through.
  def broker_params
    params.require(:broker).permit(:approved, :email) 
  end

end

app/controllers/brokers/dashboard_controller.rb
class Brokers::DashboardController < ApplicationController
  include StocksHelper
  # before_action :get_broker
  # before_action :get_stock

  def amzn
    symbol = "amzn"         # product
    get_data(symbol)
  end

  def fb
    symbol = "fb"           # product
    get_data(symbol)
  end

  def twtr
    symbol = "twtr"         # product
    get_data(symbol)
  end

  def nflx
    symbol = "nflx"         # product
    get_data(symbol)
  end


  private
  
  def stock_params
    params.require(:stocks).permit(:assets, :balance, :transaction)
  end

  def get_broker
    @broker = Broker.find_by_id("id: #{current_broker.id}").last
  end

  def get_stock
    @stock =  @broker.stocks.find_by_id(@broker.id, current_broker.id) 
  end

end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  include StocksHelper

  def amzn
    @symbol = "amzn"         # stock name
    get_data(@symbol)        # helper  app/helpers/stocks_helper.rb
    @wallet = User.find(current_user.id).wallet.to_f
    @stock = User.find(current_user.id).stocks.find_by_stock_name(@symbol).asset.to_f
  end

  def fb
    @symbol = "fb"           # product
    get_data(@symbol)        # helper  app/helpers/stocks_helper.rb
    @wallet = User.find(current_user.id).wallet.to_f
    @stock = User.find(current_user.id).stocks.find_by_stock_name(@symbol).asset.to_f
  end

  def twtr
    @symbol = "twtr"         # product
    get_data(@symbol)        # helper  app/helpers/stocks_helper.rb
    @stock = User.find(current_user.id).stocks.find_by_stock_name(@symbol).asset.to_f
    @wallet = User.find(current_user.id).wallet.to_f
  end

  def nflx
    @symbol = "nflx"         # product
    get_data(@symbol)        # helper  app/helpers/stocks_helper.rb
    @wallet = User.find(current_user.id).wallet.to_f
    @stock = User.find(current_user.id).stocks.find_by_stock_name(@symbol).asset.to_f
  end

  def buy_amzn
    @symbol = "amzn"          # stock name
    @user = User.find(current_user.id)
    @stock_target = @user.stocks.find_by_stock_name(@symbol)
    @wallet_new = @user.update(wallet: @user.wallet - 10)
    @last_price = Stock.sandbox.quote(@symbol).latest_price
    @stock_new = @user.stocks.find_by_stock_name(@symbol).update(asset: @stock_target.asset + 10/@last_price.to_f)
    redirect_to users_buy_path
  end

  def buy_fb
    @symbol = "fb"          # stock name
    @user = User.find(current_user.id)
    @stock_target = @user.stocks.find_by_stock_name(@symbol)
    @wallet_new = @user.update(wallet:@user.wallet - 10)
    @last_price = Stock.sandbox.quote(@symbol).latest_price
    @stock_new = @user.stocks.find_by_stock_name(@symbol).update(asset: @stock_target.asset + 10/@last_price.to_f)
    redirect_to users_buyfb_path
  end

  def buy_nflx
    @symbol = "nflx"          # stock name
    @user = User.find(current_user.id)
    @stock_target = @user.stocks.find_by_stock_name(@symbol)
    @wallet_new = @user.update(wallet:@user.wallet - 10)
    @last_price = Stock.sandbox.quote(@symbol).latest_price
    @stock_new = @user.stocks.find_by_stock_name(@symbol).update(asset: @stock_target.asset + 10/@last_price.to_f)
    redirect_to users_buynflx_path
  end

  def buy_twtr
    @symbol = "twtr"          # stock name
    @user = User.find(current_user.id)
    @stock_target = @user.stocks.find_by_stock_name(@symbol)
    @wallet_new = @user.update(wallet:@user.wallet - 10)
    @last_price = Stock.sandbox.quote(@symbol).latest_price
    @stock_new = @user.stocks.find_by_stock_name(@symbol).update(asset: @stock_target.asset + 10/@last_price.to_f)
    redirect_to users_buytwtr_path
  end

  private
  
  def stock_params
    params.require(:stocks).permit(:assets, :balance, :transaction)
  end

  def get_stock
    @stock =  @user.stocks.find_by_id(@user.id, current_user.id) 
  end

end

app/helpers/admins/dashboard_helper.rb
module Admins::DashboardHelper
end

app/helpers/brokers/dashboard_helper.rb
module Brokers::DashboardHelper
    def transact_buy(transaction)
        balance = balance - (transaction * client.quote(stock_name).latest_price)
        assets = assets + transaction
    end

    def transact_sell(transaction)
        balance = balance + (transaction * client.quote(stock_name).latest_price)
        assets = assets - transaction
    end

end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/views/admins/dashboard/index.html.slim
.d-flex.justify-content-end.mb-4
  h6
    strong.text-muted
      | Admins::Dashboard
    = link_to "👤", edit_admin_registration_path, class: "btn badge bg-info text-white mx-1"

.d-flex.justify-content-center
  h4
   strong 
    | User List

.card.my-4
  .card-body
    table.table
      thead
        tr
          th.text-center scope="col"  
            | Brokers's Accounts: 
          th.text-center scope="col"  
            | Wallet: 
          th.text-center scope="col"  
            | Stocks/Asset: 
          th.text-center scope="col"  
            | Status:
    
      tbody
        - @brokers.each do |broker|
          tr
            td.text-center.align-middle scope="row" 
              = broker.email
            td.text-center.align-middle scope="row" 
              span 
                | $ 
                = broker.wallet
            td.text-center.align-middle scope="row" 
              = broker.stocks.select {|x| !x.asset.zero? }.map{|x|  "#{x.stock_name.upcase}:#{x.asset}" }.join(', ')
            td.text-center
              - unless broker.approved
                strong.mx-4.badge.btn-warning.rounded-pill
                  .mx-2.my-1
                    = link_to 'Pending...', admins_approved_path(broker), method: :patch, class: "text-dark"
              - else 
                strong.mx-4.badge.bg-success.text-white.rounded-pill
                  .mx-2.my-1
                    | Approved


.card.my-4
  .card-body
    table.table
      thead
        tr
          th.text-center scope="col"  
            | Buyer's Accounts: 
          th.text-center scope="col"  
            | Wallet: 
          th.text-center scope="col"  
            | Stocks/Asset: 
          th.text-center scope="col"  
            | Status
      - @users.each do |user|
        byebug 
        tbody
          tr
            td.text-center.align-middle scope="row" 
              = user.email
            td.text-center.align-middle scope="row" 
              span 
                | $ 
                = user.wallet
            td.text-center.align-middle scope="row" 
              =  user.stocks.select {|x| !x.asset.zero? }.map{|x|  "#{x.stock_name.upcase}:#{x.asset}" }.join(', ')
            td.text-center
              strong.mx-4.badge.bg-success.text-white.rounded-pill
                .mx-2.my-1
                  | Approved