config/routes.rb
Rails.application.routes.draw do

  resources :stocks
  
  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  devise_scope :admin do
    authenticated :admin do
      namespace :admins do
        get 'dashboard/index', as: :authenticated_root
        patch 'dashboard/:id/update',to:'dashboard#update' , as: :approved
      end
    end
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    authenticated :user do
      namespace :users do
        get 'dashboard/amzn', as: :authenticated_root
        get 'dashboard/fb'
        get 'dashboard/twtr'
        get 'dashboard/nflx'
        post 'dashboard/amzn',to:'dashboard#buy_amzn', as: :buy
        post 'dashboard/fb',to:'dashboard#buy_fb', as: :buyfb
        post 'dashboard/twtr',to:'dashboard#buy_twtr', as: :buytwtr
        post 'dashboard/nflx',to:'dashboard#buy_nflx', as: :buynflx
      end
    end
  end
  
  devise_scope :broker do
    authenticated :broker do
      namespace :brokers do
        get 'dashboard/amzn', as: :authenticated_root
        get 'dashboard/fb'
        get 'dashboard/twtr'
        get 'dashboard/nflx'
        post 'dashboard/amzn',to:'dashboard#buy_amzn', as: :buy           #this should be sell
        post 'dashboard/fb',to:'dashboard#buy_fb', as: :buyfb             #this should be sell
        post 'dashboard/twtr',to:'dashboard#buy_twtr', as: :buytwtr       #this should be sell
        post 'dashboard/nflx',to:'dashboard#buy_nflx', as: :buynflx       #this should be sell
      end
    end
  end

  devise_for :brokers, path: 'broker', controllers: {
    sessions: 'brokers/sessions',
    registrations: 'brokers/registrations'
  }

  root to: "home#index"
end

app/views/layouts/_ticker.html.slim
.d-flex.justify-content-end.mb-4
  h6
    if 
      - if admin_signed_in?
        strong.text-muted
          | Admin::Dashboard
        = link_to "👤", edit_admin_registration_path, class: "btn badge bg-info mx-1"

      - if user_signed_in?
        strong.text-muted
          | Buyers::Dashboard
        = link_to "👤", edit_user_registration_path, class: "btn badge bg-info mx-1"

      - if broker_signed_in?
        strong.text-muted
          | Broker::Dashboard
        = link_to "👤", edit_broker_registration_path, class: "btn badge bg-info mx-1"

.d-flex.justify-content-center
  .row
    h4.text-center
      strong
        | Trading View


.col.col-lg-3.mb-4 style='width: 200px;'
  .btn-group-vertical.position-absolute.top-8.start-0 aria-label=("Vertical button group") role="group" 



    - unless user_signed_in?
      = link_to "AMZN", brokers_authenticated_root_path, class: "btn badge btn-info text-white p-2"
      = link_to "FB", brokers_dashboard_fb_path, class: "btn badge btn-info text-white p-2"
      = link_to "TWTR", brokers_dashboard_twtr_path, class:"btn badge btn-info text-white p-2"
      = link_to "NFLX", brokers_dashboard_nflx_path, class: "btn badge btn-info text-white p-2"
    - else
      = link_to "AMZN", users_authenticated_root_path, class: "btn badge btn-info text-white p-2"
      = link_to "FB", users_dashboard_fb_path, class: "btn badge btn-info text-white p-2"
      = link_to "TWTR", users_dashboard_twtr_path, class:"btn badge btn-info text-white p-2"
      = link_to "NFLX", users_dashboard_nflx_path, class: "btn badge btn-info text-white p-2"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | JTradingApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    link[rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous"]
    script[src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"]
    / = javascript_include_tag "https://www.gstatic.com/charts/loader.js"
    / script[src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"]
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    / script src="//cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js" type="text/javascript" 
    / script src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js" type="text/javascript" 
    / script src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.gammel.js" type="text/javascript" 
    / script src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.zune.js" type="text/javascript" 
    / script src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.carbon.js" type="text/javascript" 
    / script src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.ocean.js" type="text/javascript" `

  body
    .container.fixed_top_end.col-12
    
      .d-flex.flex-row-reverse
        p.alert.badge.bg-success.text-dark.text-white
          = notice
        p.alert.badge.bg-warning.text-dark
          = alert


    .d-flex.mb-4
      .btn-group-sm role="group" aria-label="Basic outlined button group"
        = link_to 'News', root_path, class: "btn btn-primary text-white mx-1"
        - if admin_signed_in?
          = link_to 'Sign Out as Admin', destroy_admin_session_path, method: :delete, class: "btn btn-primary text-white"
        - elsif !user_signed_in? && !broker_signed_in?
          = link_to "Admin", new_admin_session_path, class: "btn btn-primary text-white mx-1"
        - if user_signed_in?
          = link_to 'Sign Out as Buyer', destroy_user_session_path, method: :delete, class: "btn btn-primary text-white"
        - elsif !admin_signed_in? && !broker_signed_in?
          = link_to "Buyer", new_user_session_path, class: "btn btn-primary text-white mx-1"
        - if broker_signed_in?
          = link_to 'Sign Out as Broker', destroy_broker_session_path, method: :delete, class: "btn btn-primary text-white"
        - elsif !admin_signed_in? && !user_signed_in?
          = link_to "Broker", new_broker_session_path, class: "btn btn-primary text-white mx-1"

    = yield

    / .col.col-lg-3.mb-4 style='width: 200px;'
		/ 	br/
		/ 	br/
		/ 	#list-tab.list-group.position-absolute.top-7.start-0 role="tablist" 
		/ 		a#list-home-list.list-group-item.list-group-item-action.active aria-controls="home" data-bs-toggle="list" href="#list-home" role="amzm"  AMZN
		/ 		a#list-profile-list.list-group-item.list-group-item-action aria-controls="profile" data-bs-toggle="list" href="#list-profile" role="tab"  FB
		/ 		a#list-messages-list.list-group-item.list-group-item-action aria-controls="messages" data-bs-toggle="list" href="#list-messages" role="tab" TWTR
		/ 		a#list-settings-list.list-group-item.list-group-item-action aria-controls="settings" data-bs-toggle="list" href="#list-settings" role="tab"  NFLX